# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'jbcook/kali-light'
  config.vm.box_version = '1.0.0'

  config.vm.provider 'virtualbox' do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = 1024
    # Customize the amount of cpu on the VM:
    vb.cpus = 1
  end

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
    apt-get install -y puppet
    puppet module install puppetlabs-vcsrepo
  SHELL

  config.vm.provision :puppet
end
